name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the React app
        run: npm run build

      - name: Build Docker Image
        run: docker build -t your-app-name .

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Push Docker Image to Heroku
  run: |
    docker tag your-app-name registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web


      - name: Deploy Heroku App
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
