name: Build and Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test  # Assuming you have a test script in your package.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker image
        run: |
          docker build . -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Push Docker image to Heroku
        run: |
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release the app on Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
