name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: "20" # Updated to Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the React app
        run: npm run build

      - name: Build Docker Image
        run: docker build -t your-app-name .

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Accept Heroku Terms of Service
        run: |
          curl -n -X PATCH https://api.heroku.com/account \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -d '{ "terms_of_service": true }'

      - name: Push Docker Image to Heroku
        run: |
          docker tag your-app-name registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Deploy Heroku App
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
